int ProfileInitialize_online ();
int EnableCounter (int counter);
int SetTimerSamplingPeriod (int interval_ms);
int StartProfiling ();
int StopProfiling ();
int ProfileClose ();
samples_pair_t ReadAllEnabledCounters ();
int ReadAllEnabledCounters_PwrSample_elapsedTimeMs (void* handle, int idx);
uint ReadAllEnabledCounters_PwrSample_recordId (void* handle, int idx);
int ReadAllEnabledCounters_PwrSample_numOfCounter (void* handle, int idx);
int ReadAllEnabledCounters_counterValues_counterID (void* handle, int idx, int counter_idx);
int ReadAllEnabledCounters_counterValues_valueCnt (void* handle, int idx, int counter_idx);
float ReadAllEnabledCounters_counterValues_data (void* handle, int idx, int counter_idx);
int GetSupportedCounters_num ();
int GetCounterDesc_counterID (int idx);
int GetCounterDesc_deviceId (int idx);
int GetCounterDesc_devType (int idx);
int GetCounterDesc_devInstanceId (int idx);
char* GetCounterDesc_name (int idx);
char* GetCounterDesc_description (int idx);
int GetCounterDesc_category (int idx);
int GetCounterDesc_aggregation (int idx);
double GetCounterDesc_minValue (int idx);
double GetCounterDesc_maxValue (int idx);
int GetCounterDesc_units (int idx);
int GetCounterDesc_isParentCounter (int idx);
