int ProfileInitialize (int mode);
int EnableCounter (int counter);
int SetTimerSamplingPeriod (int interval_ms);
int StartProfiling ();
int StopProfiling ();
int ProfileClose ();
samples_pair_t ReadAllEnabledCounters ();
int GetSupportedCounters_num ();
int GetCounterDesc_counterID (int idx);
int GetCounterDesc_deviceID (int idx);
int GetCounterDesc_devType (int idx);
int GetCounterDesc_devInstanceID (int idx);
char* GetCounterDesc_name (int idx);
char* GetCounterDesc_description (int idx);
int GetCounterDesc_category (int idx);
int GetCounterDesc_aggregation (int idx);
double GetCounterDesc_minValue (int idx);
double GetCounterDesc_maxValue (int idx);
int GetCounterDesc_units (int idx);
int GetCounterDesc_isParentCounter (int idx);
